### ISSUE TITLE
Installing via `go get` does not work

### ISSUE THREAD

**Issue by klingtnet** [urandom/readeef#13]
Sorry for opening so much issues (#11, #12) but this is the last one for now.
I've installed `readeef` via `go get github.com/urandom/readeef/cmd/readeef-server` on my laptop but it panics on the first start with the following message:

```sh
$ /tmp: readeef-server
FATA[0000] Fatal error: runtime error: cgo argument has Go pointer to Go pointer
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x80
main.main.func1(0x7f1811bbc1f0, 0xc82042a8c0)
	/home/andreas/.go/src/github.com/urandom/readeef/cmd/readeef-server/main.go:45 +0x53
panic(0x1037a60, 0xc8202ab540)
	/usr/lib/go/src/runtime/panic.go:443 +0x4e9
github.com/mattn/go-sqlite3._cgoCheckPointer0(0xe40ee0, 0xc82010e394, 0x0, 0x0, 0x0, 0xdf21e0)
	github.com/mattn/go-sqlite3/_obj/_cgo_gotypes.go:73 +0x4d
github.com/mattn/go-sqlite3.(*SQLiteStmt).bind(0xc82008acd0, 0xc82010e420, 0xb, 0xb, 0x0, 0x0)
	/home/andreas/.go/src/github.com/mattn/go-sqlite3/sqlite3.go:804 +0xa39
github.com/mattn/go-sqlite3.(*SQLiteStmt).Exec(0xc82008acd0, 0xc82010e420, 0xb, 0xb, 0x0, 0x0, 0x0, 0x0)
	/home/andreas/.go/src/github.com/mattn/go-sqlite3/sqlite3.go:836 +0x7b
database/sql.resultFromStatement(0x7f1811bbc428, 0xc820402000, 0x7f1811bbc4e8, 0xc82008acd0, 0xc82040d118, 0xb, 0xb, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/database/sql/sql.go:1502 +0x3d7
database/sql.(*Stmt).Exec(0xc8200a4380, 0xc82040d118, 0xb, 0xb, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/database/sql/sql.go:1470 +0x2ae
github.com/urandom/readeef/content/sql.(*User).Update(0xc820460b40)
	/home/andreas/.go/src/github.com/urandom/readeef/content/sql/user.go:95 +0xa86
github.com/urandom/readeef/api.initAdminUser(0x7f1811bbc588, 0xc82043c060, 0xc8202ab040, 0x0, 0x8, 0x0, 0x0)
	/home/andreas/.go/src/github.com/urandom/readeef/api/api.go:269 +0x297
github.com/urandom/readeef/api.RegisterControllers(0x0, 0x0, 0x1f90, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc8203b2be0, 0x9, ...)
	/home/andreas/.go/src/github.com/urandom/readeef/api/api.go:68 +0x638
main.main()
	/home/andreas/.go/src/github.com/urandom/readeef/cmd/readeef-server/main.go:70 +0x970
```

**Comment by klingtnet** [comment]
I'm using `go version go1.6.2 linux/amd64` on Arch Linux.

**Comment by urandom** [comment]
Since I'm personally not using cgo, it might be possible if you've already had some of my dependencies, but as an older checkout (specifically go-sqlite3).

Do you mind doing `go get -u github.com/urandom/readeef/cmd/readeef-server` to get new versions of the dependencies?

**Comment by klingtnet** [comment]
Great, this fixed the problem!
